ALTER TABLE public.tournament_webpage
ADD COLUMN reg_begins TIMESTAMPTZ,
ADD COLUMN early_reg_ends TIMESTAMPTZ,
ADD COLUMN late_reg_ends TIMESTAMPTZ,
ADD COLUMN early_reg_price NUMERIC DEFAULT 0,
ADD COLUMN late_fee NUMERIC DEFAULT 0,
ADD COLUMN collegiate_discount NUMERIC DEFAULT 0,
ADD COLUMN price_per_event NUMERIC DEFAULT 0;